-- CreateTable
CREATE TABLE "models" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "short_name" TEXT,
    "slug" TEXT NOT NULL,
    "developer" TEXT NOT NULL,
    "release_date" TEXT,
    "version" TEXT,
    "family" TEXT,
    "model_series" TEXT,
    "branch_type" TEXT,
    "description" TEXT,
    "logo_url" TEXT,
    "model_type" TEXT NOT NULL,
    "architecture" TEXT,
    "params_total" REAL,
    "params_active" REAL,
    "context_window" INTEGER,
    "max_output_tokens" INTEGER,
    "training_tokens" REAL,
    "vocab_size" INTEGER,
    "knowledge_cutoff" TEXT,
    "fine_tuning_method" TEXT,
    "layers" INTEGER,
    "attention_mechanism" TEXT,
    "license" TEXT,
    "commercial_use_allowed" BOOLEAN,
    "pricing_input" REAL,
    "pricing_output" REAL,
    "free_tier_available" BOOLEAN,
    "modalities_input" TEXT,
    "modalities_output" TEXT,
    "languages" TEXT,
    "supports_tool_use" BOOLEAN,
    "supports_json_mode" BOOLEAN,
    "supports_vision" BOOLEAN,
    "coding_capable" BOOLEAN,
    "supports_reasoning" BOOLEAN,
    "model_size" REAL,
    "tensor_type" TEXT,
    "model_format" TEXT,
    "num_files" INTEGER,
    "quantization_available" TEXT,
    "inference_frameworks" TEXT,
    "score_arena_elo" INTEGER,
    "benchmarks" TEXT,
    "url_paper" TEXT,
    "url_huggingface" TEXT,
    "url_demo" TEXT,
    "url_github" TEXT,
    "url_api_docs" TEXT,
    "url_blog" TEXT,
    "url_website" TEXT,
    "metadata" TEXT,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "models_slug_key" ON "models"("slug");
